--TYPES OF JOINS
CREATE DATABASE EMPLOYEE

USE EMPLOYEE

CREATE TABLE EMPLOYEE_INFO(EMP_ID INT PRIMARY KEY, EMP_NAME VARCHAR(20), EMP_EMAIL VARCHAR(20))

CREATE TABLE DEPARTMENT(DEP_ID INT PRIMARY KEY ,REF_ID INT, DEP_NAME VARCHAR(20))

INSERT INTO EMPLOYEE_INFO(EMP_ID ,EMP_NAME) VALUES (101,'SHREYA'),(102,'SAI'),(103,'RM');
INSERT INTO DEPARTMENT(DEP_ID, REF_ID , DEP_NAME) VALUES(20,101,'CB'),(21,102,'TB'),(22,101,'CBE')
INSERT INTO DEPARTMENT VALUES (23,103,'CBB')

SELECT * FROM EMPLOYEE_INFO
SELECT * FROM DEPARTMENT

--INNER JOIN
SELECT * 
FROM EMPLOYEE_INFO
INNER JOIN DEPARTMENT
ON EMPLOYEE_INFO.EMP_ID = DEPARTMENT.REF_ID

SELECT EMP_NAME
FROM EMPLOYEE_INFO
INNER JOIN DEPARTMENT
ON EMPLOYEE_INFO.EMP_ID =DEPARTMENT.REF_ID

SELECT DEP_NAME
FROM EMPLOYEE_INFO
INNER JOIN DEPARTMENT
ON EMPLOYEE_INFO.EMP_ID =DEPARTMENT.REF_ID

--LEFT JOIN
SELECT * 
FROM EMPLOYEE_INFO
LEFT JOIN DEPARTMENT
ON EMPLOYEE_INFO.EMP_ID = DEPARTMENT.REF_ID

SELECT DEP_NAME
FROM DEPARTMENT
LEFT JOIN EMPLOYEE_INFO
ON DEPARTMENT.REF_ID = EMPLOYEE_INFO.EMP_ID

--RIGHT JOIN
SELECT * 
FROM DEPARTMENT AS D
RIGHT JOIN EMPLOYEE_INFO AS E
ON D.REF_ID =E.EMP_ID

SELECT EMP_NAME
FROM EMPLOYEE_INFO AS E
RIGHT JOIN DEPARTMENT AS D
ON E.EMP_ID =D.REF_ID

--FULL JOIN
SELECT *
FROM DEPARTMENT
LEFT JOIN EMPLOYEE_INFO
ON DEPARTMENT.REF_ID = EMPLOYEE_INFO.EMP_ID
UNION
SELECT *
FROM DEPARTMENT AS D
RIGHT JOIN EMPLOYEE_INFO AS E
ON D.REF_ID =E.EMP_ID

SELECT *
FROM DEPARTMENT AS D
FULL JOIN EMPLOYEE_INFO AS E
ON D.REF_ID =E.EMP_ID

-- EXCLUSIVE LEFT JOIN

SELECT *
FROM EMPLOYEE_INFO AS E
LEFT JOIN DEPARTMENT AS D
ON E.EMP_ID=D.REF_ID
WHERE D.REF_ID IS NULL

-- EXCLUSIVE RIGHT JOIN

SELECT *
FROM EMPLOYEE_INFO AS E
RIGHT JOIN DEPARTMENT AS D
ON E.EMP_ID=D.REF_ID
WHERE D.REF_ID IS NULL

--CROSS JOIN

SELECT * FROM EMPLOYEE_INFO CROSS JOIN DEPARTMENT

--SELF JOIN

ALTER TABLE EMPLOYEE_INFO 
ADD PROJECT_TEAM INT;

SELECT * FROM EMPLOYEE_INFO

UPDATE  EMPLOYEE_INFO
SET PROJECT_TEAM = 102 
WHERE EMP_ID=101

UPDATE  EMPLOYEE_INFO
SET PROJECT_TEAM = 103 
WHERE EMP_ID=102

UPDATE  EMPLOYEE_INFO
SET PROJECT_TEAM = 102 
WHERE EMP_ID=103

SELECT E.EMP_ID , E.EMP_NAME,
(E1.EMP_NAME) AS PROJECT_TEAM 
FROM EMPLOYEE_INFO AS E
INNER JOIN EMPLOYEE_INFO AS E1
ON E.PROJECT_TEAM =E1.EMP_ID

