USE SCHOOLDB


SELECT * FROM Courses
SELECT * FROM Enrollments
SELECT * FROM Students

ALTER TABLE STUDENTS 
ADD STUD_MARKS INT;

UPDATE STUDENTS
SET STUD_MARKS= 70
WHERE StudentID=2

--COUNT 
SELECT COUNT(*) AS NO_OF_STUDENT
FROM Students

SELECT COUNT(STUD_MARKS) AS MARKS FROM Students;

SELECT COUNT(*) FROM Courses WHERE CourseName = 'math';


--SUM
SELECT SUM(STUD_MARKS)AS SUM_OF_MARKS FROM Students;

--AVG

SELECT AVG(STUD_MARKS)AS AVG_MARKS FROM Students;

--MIN

SELECT MIN(STUD_MARKS) AS MINIMUM_MARKS FROM Students;

--MAX 

SELECT MAX(STUD_MARKS) AS MAXIMUM_MARKS FROM Students;

