CREATE DATABASE STUDENT;
USE STUDENT;
CREATE TABLE STUDENT_INFO(STUDENT_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
CGPA INT,
ENROLLEMENT_DATE DATE,
MAJOR VARCHAR(20))

CREATE TABLE SCHOLARSHIP(
STUDENT_ID_REF INT PRIMARY KEY,
SCHOLARSHIP_AMOUNT INT,
SCHOLARSHIP_DATE DATE)

INSERT INTO STUDENT_INFO VALUES(201,'SHIVANSH','MAHAJAN',8,'2025-09-01','COMPUTER SCIENCE')
INSERT INTO STUDENT_INFO VALUES(202,'SHIVA','KUMAR',9,'2025-09-02','INFORMATION SCIENCE')

INSERT INTO SCHOLARSHIP VALUES(201,345670,'2025-11-09')
INSERT INTO SCHOLARSHIP VALUES(202,367890,'2025-11-08')

SELECT * FROM STUDENT_INFO
SELECT FIRST_NAME FROM STUDENT_INFO
SELECT LAST_NAME FROM STUDENT_INFO
SELECT CGPA FROM STUDENT_INFO
SELECT ENROLLEMENT_DATE FROM STUDENT_INFO
SELECT MAJOR FROM STUDENT_INFO

UPDATE SCHOLARSHIP SET SCHOLARSHIP_AMOUNT = 50000 
WHERE STUDENT_ID_REF = 201

ALTER TABLE STUDENT_INFO ADD EMAIL VARCHAR(25);
ALTER TABLE STUDENT_INFO ALTER COLUMN EMAIL VARCHAR(25)
ALTER TABLE STUDENT_INFO DROP COLUMN EMAIL;

SELECT SCHOLARSHIP_AMOUNT FROM SCHOLARSHIP WHERE STUDENT_ID_REF =201

SELECT * FROM SCHOLARSHIP

DELETE FROM SCHOLARSHIP WHERE STUDENT_ID_REF=201

SELECT MAJOR 
FROM STUDENT_INFO
WHERE STUDENT_ID =202

SELECT name FROM sys.server_principals WHERE type_desc = 'SQL_LOGIN';

GRANT SELECT ON SCHOLARSHIP TO testuser ;

USE STUDENT;
GO

EXECUTE AS USER = 'testuser';
SELECT * FROM SCHOLARSHIP;

REVERT;

REVOKE SELECT ON SCHOLARSHIP FROM testuser;

BEGIN TRANSACTION;

INSERT INTO STUDENT_INFO VALUES(203,'SHI','M',7,'2025-09-01','COMPUTER SCIENCE')

SAVE TRANSACTION SavePoint1;

DELETE FROM STUDENT_INFO WHERE STUDENT_ID=203

ROLLBACK TRANSACTION SavePoint1;

COMMIT

CREATE DATABASE DUMMY
CREATE TABLE STUDENT(STUDENT_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
CGPA INT,
ENROLLEMENT_DATE DATE,
MAJOR VARCHAR(20))

INSERT INTO STUDENT VALUES(201,'SHIVANSH','MAHAJAN',8,'2025-09-01','COMPUTER SCIENCE')
INSERT INTO STUDENT VALUES(202,'SHIVA','KUMAR',9,'2025-09-02','INFORMATION SCIENCE')

SELECT * FROM STUDENT

ALTER TABLE Student DROP COLUMN MAJOR;

DROP TABLE STUDENT

DROP DATABASE DUMMY

TRUNCATE TABLE Student;
